using Almanna;

namespace PluginService.Model.DB.Implementation {
	
	/**
	 * Almanna Implementation for class "PluginInstall".
	 * Generated by almanna-generate.
	 */
	public class PluginInstall : PluginService.Model.DB.Entity.PluginInstall {
		public override void register_entity() {
			base.register_entity();
		}

		public override void save() {
			base.save();
			var plugin = new Search<Plugin>().eq( "plugin_id", this.plugin_id ).single();
			if ( plugin != null ) {
				plugin.installs++;
				plugin.save();
			}
		}
	}
}
