using Almanna;

namespace PluginService.Model.DB.Implementation {
	
	/**
	 * Almanna Implementation for class "PluginDocumentation".
	 * Generated by almanna-generate.
	 */
	public class PluginDocumentation : PluginService.Model.DB.Entity.PluginDocumentation {
		public override void register_entity() {
			base.register_entity();
		}
	}
}
