using Almanna;
namespace PluginService.Model.DB {
	/**
	 * Almanna loader.
	 * Generated by generate-schema.pl.
	 */
	
	public class AlmannaLoader : Object,Almanna.Loader {
		public void load_entities() {
			Repo.add_entity( typeof(Author) );
			Repo.add_entity( typeof(Plugin) );
			Repo.add_entity( typeof(PluginDocumentation) );
			Repo.add_entity( typeof(PluginHistory) );
		}
	}
}

