using Almanna;
namespace PluginService.Model.DB {
	/**
	 * Almanna loader.
	 * Generated by almanna-generate.
	 */
	
	public class AlmannaLoader : Object,Almanna.Loader {
		public void load_entities() {
			Repo.add_entity( typeof(PluginService.Model.DB.Implementation.Author) );
			Repo.add_entity( typeof(PluginService.Model.DB.Implementation.Plugin) );
			Repo.add_entity( typeof(PluginService.Model.DB.Implementation.PluginDocumentation) );
			Repo.add_entity( typeof(PluginService.Model.DB.Implementation.PluginHistory) );
			Repo.add_entity( typeof(PluginService.Model.DB.Implementation.PluginInstall) );
		}
	}
}
