using Almanna;

namespace PluginService.Model.DB.Entity {
	
	/**
	 * Almanna Entity for table "author".
	 * Generated by almanna-generate.
	 */
	public class Author : Almanna.Entity {
		public override string entity_name { owned get { return "author"; } }
		public int author_id { get; set; }
		public int active { get; set; }
		public string name { get; set; }
		public string email { get; set; }
		public string url { get; set; }
		public string password_hash { get; set; }
		public string api_key { get; set; }
		public DateTime date_created { get; set; }
		public DateTime date_modified { get; set; }
		
		public override void register_entity() {
			add_column( new Column<int>.with_name_type( "author_id", "int4" ) );
			columns["author_id"].size = 4;
			columns["author_id"].is_sequenced = true;
			
			add_column( new Column<int>.with_name_type( "active", "int4" ) );
			columns["active"].size = 4;
			columns["active"].is_nullable = true;
			
			add_column( new Column<string>.with_name_type( "name", "varchar" ) );
			
			add_column( new Column<string>.with_name_type( "email", "varchar" ) );
			
			add_column( new Column<string>.with_name_type( "url", "varchar" ) );
			columns["url"].is_nullable = true;
			
			add_column( new Column<string>.with_name_type( "password_hash", "bpchar" ) );
			columns["password_hash"].is_nullable = true;
			
			add_column( new Column<string>.with_name_type( "api_key", "bpchar" ) );
			columns["api_key"].is_nullable = true;
			
			add_column( new Column<DateTime>.with_name_type( "date_created", "timestamp" ) );
			columns["date_created"].is_nullable = true;
			
			add_column( new Column<DateTime>.with_name_type( "date_modified", "timestamp" ) );
			columns["date_modified"].is_nullable = true;
			
			try {
				set_primary_key("author_id");
			} catch (EntityError e) {
				stderr.printf( "Error adding primary key to entity: %s\n", e.message );
			}
		}
	}
}
